--- #YAML:1.0
name:               Net-Amazon-DynamoDB
version:            v0.1.3
abstract:           Simple interface for Amazon DynamoDB
author:
    - Ulrich Kautz <uk@fortrabbit.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    DateTime:             0
    DateTime::Format::HTTP:  0
    Digest::SHA:          0
    HTTP::Request:        0
    JSON:                 0
    LWP::UserAgent:       0
    Moose:                1
    Net::Amazon::AWSSign:  0
    perl:                 5.010000
    Test::More:           0
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
